---
replicaCount: 1

image:
  tag: "v0.1.0"
  pullPolicy: "IfNotPresent"

# resources:
#   limits:
#     memory: "40Mi"
#     cpu: "50m"
#   requests:
#     memory: "25Mi"
#     cpu: "15m"

# Configuration that you wish to keep secret can be read as environment
# variables from a secret. A common use case is to configure auth credentials
# by setting the following variables in the secret:
#
# AMIFY_HOOK_AUTH_USERNAME
# AMIFY_HOOK_AUTH_PASSWORD
# AMIFY_NTFY_AUTH_USERNAME
# AMIFY_NTFY_AUTH_PASSWORD
envSecretName: ""

config:
  hook:
    auth:
      enable: false
      username: ""
      password: ""
    log:
      level: "info"  # possible values: "debug", "info", "warn", "error"
      format: "text" # possible values: "text", "json"
    # sets the period after which the webhook must be forcefully terminated. A
    # value of 0 implies no forceful termination.
    terminationGracePeriod: 0
  ntfy:
    baseUrl: ""
    auth:
      enable: false
      username: ""
      password: ""
    notification:
      # Topic can either be a hardcoded string or a gval expression
      # that evaluates to a string
      topic: ""
      # Priority reference: https://docs.ntfy.sh/publish/#message-priority
      # Can either be a hardcoded string or a gval expression that
      # evaluates to a string
      priority: |
        Status == "firing" ? "urgent" : "default"
      # Tags with no condition are always included
      # Emoji shortcode reference: https://docs.ntfy.sh/emojis/
      tags:
        - tag: "rotating_light,construction"
          condition: |
            Status == "firing"
        - tag: "white_check_mark,confetti_ball"
          condition: |
            Status == "resolved"
      title: |
          {{ if eq .Status "resolved" }}Resolved: {{ end }}{{ index .Annotations "summary" }}
      description: |
          {{ index .Annotations "description" }}
